### ISSUE TITLE
"Ballast is damaged and can't be opened." On latest Mojave Beta.

### ISSUE THREAD

**Issue by nevara** [jamsinclair/ballast#1]
<img width="488" alt="screenshot 2018-08-17 at 21 26 39" src="https://user-images.githubusercontent.com/18462495/44285082-3dad5880-a264-11e8-8e9c-49c3faa0312b.png">

**Comment by chilicoffee** [comment]
Duplicate of https://github.com/jamsinclair/ballast/issues/2

**Comment by jamsinclair** [comment]
@nevara Thanks for pointing this out. 

I've compiled the app using the latest Xcode beta. Let me know if this works 😄 
https://github.com/jamsinclair/ballast/releases/download/v1.0.0/ballast-mojave.dmg

**Comment by nevara** [comment]
It can be launched now 👍
