### ISSUE TITLE
Install through brew

### ISSUE THREAD

**Issue by RolfKoenders** [jamsinclair/ballast#12]
Thanks for this tool! Lifesaver! :pray:

It would be great to install this through Brew? I found the following which might help:  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by markphelps** [comment]
You could just create the formula on the main homebrew/core repo. This way you wouldnt have to maintain a tap of your own. They even provided a `brew create` command to easily create a formula.

https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#grab-the-url

**Comment by jamsinclair** [comment]
I appreciate the suggestion, but I don't have time to dedicate to educating myself in this area. If you're experienced and have the know how, submit a PR with the instructions 🙇‍♂️🙇‍♂️🙇‍♂️どうも

Would love to help out but don't have the time given the nature of the long brew documentation.

**Comment by jamsinclair** [comment]
Can now be installed via `brew cask install ballast`

Will update Readme with new installation docs soon.
