### ISSUE TITLE
[feature request] add switch back to internal microphone whenever this setting is changed 

### ISSUE THREAD

**Issue by PatrykDampc** [jamsinclair/ballast#13]
Hello again, I love your simple app and i though that it would be a great idea if you could implement small option kind of similar to ballast main purpose -> to switch back to internal microphone when bluetooth headset is connected and whenever that setting is being changed by some system event or sth, because macOS default behavior produces uncomfortable situations with it.

Here is discussion about that 'bug' and automator script for fix, so i believe that can be simple for you to implement that feature in future releases

https://apple.stackexchange.com/questions/287399/how-to-always-use-internal-microphone

cheers :)

**Comment by jamsinclair** [comment]
@PatrykDampc Thanks for the suggestion, for the moment I want to keep this app simple in its objective. If more audio related feature requests are raised in the future, I may revisit features like this.

Thanks again!
