### ISSUE TITLE
Build for 10.11.x support

### ISSUE THREAD

**Issue by jasonferrier** [jamsinclair/ballast#15]
It may still be many months until I upgrade from El Capitan but am plagued with this issue since I bought this Macbook Pro 15" in early 2013!

I'd love it if there was a release that supported 10.11.x OS X.

**Comment by jamsinclair** [comment]
@jasonferrier unfortunately my library is dependant on the library https://github.com/sindresorhus/LaunchAtLogin which requires **macOS 10.12+**

I've made quick branch [over here](https://github.com/jamsinclair/ballast/tree/osx-10.11-special) for the moment to help you out. It has the launch at login functionality removed. You can manually setup the app to launch as one of your login items.

Here is the built binary: 
https://github.com/jamsinclair/ballast/releases/download/v1.1.0-special/ballast-v1.1.0-special.zip

Let me know if it helps 😄
