### ISSUE TITLE
Switching devices causes app to exit

### ISSUE THREAD

**Issue by jasonadkison** [jamsinclair/ballast#16]
Thanks for your work, the app works great! I've been using it to fix the annoying random balance-changing issue with my Bose SC35 bluetooth headset.

One issue I've noticed is that the app exists when I disconnect my headset. I believe it's because my default output device doesn't support audio controls (an LG monitor). When I reconnect my headset I have to relaunch the app again.

Is this behavior by design? It would be great if the app would stay running when switching devices.

**Comment by jamsinclair** [comment]
@jasonadkison @jfoboss Thanks for reporting this. Totally a bug.

Should be fixed in this release: https://github.com/jamsinclair/ballast/releases/tag/v1.2.0

Let me know if it resolves your problems and I'll close the issue 😄

**Comment by jfoboss** [comment]
Thank you very much! I've tried new version and it is working great! 👍

**Comment by jasonadkison** [comment]
Works perfect! thanks @jamsinclair!
