### ISSUE TITLE
Does not open on MacOS Mojave, “ballast” is damaged

### ISSUE THREAD

**Issue by chilicoffee** [jamsinclair/ballast#2]
Steps to reproduce:
1. Download the DMG from https://github.com/jamsinclair/ballast/releases/tag/v1.0.0
2. Open DMG and copy app to Applications
3. Open app

Expected result: MacOS displays notification about unidentified developer. http://take.ms/D16v0
Actual result: MacOS displays notification that application is damaged and offers it to be moved to trash.

**Comment by chilicoffee** [comment]
To run this on Mojave, I had to build it myself with its version of Xcode.
Here is an zip archive with the app for Mojave http://take.ms/T4R7G

Steps, if anyone wants to do it themselves:

*DO THIS AT YOUR OWN RISK*
I'm not an app developer and this all could be done WAY better.. I just did some google-fu and came up with this recipe. Tested on Mojave Public Beta 6.

1. Open `terminal.app`
2. Clone the repo `$ git clone https://github.com/jamsinclair/ballast.git`
3. Install homebrew `$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
4. Install carthage with homebrew `$ brew install carthage`
5. `$ cd ballast`
6. `$ carthage update`
7. `$ open .` Finder window will open.. double click on `ballast.xcodeproj`
8. Go to `Product => Build`
9. Open finder and do `CMD + G`, paste in following `~/Library/Developer/Xcode/DerivedData/` and enter.
10. Navigate to folder `ballast-.../Build/Products/Debug/`
11. Here is the app that you have built

**Comment by jamsinclair** [comment]
@chilicoffee Thanks for looking into this 👍 

I think that is the solution, to compile from Mojave. I'll download the beta and make a new release.

**Comment by Mentis** [comment]
Same issue on macOS 10.13.6

**Comment by jamsinclair** [comment]
Hmmm turns out it's a known problem with Gatekeeper. See this thread: https://apple.stackexchange.com/a/300304/299138. 

I've created some new builds and removed codesigning. Let me know if these change anything:
https://github.com/jamsinclair/ballast/releases/tag/v1.0.1

**Comment by neptunus** [comment]
@jamsinclair For what it's worth, I'm running Mojave and the new build runs fine for me

**Comment by Mentis** [comment]
@jamsinclair this build works. Thank you!
