### ISSUE TITLE
Suggestion: equalise volume to the lower of the two volumes

### ISSUE THREAD

**Issue by Jimima** [jamsinclair/ballast#20]
Hi there! This app is great and fixes an issue I have with my USB DAC which is that the left channel is occasionally set to maximum, for reasons I can't fathom. This app works great to fix the balance issue, but seems to correct the quieter channel to match the loudest channel, which in my case is the maximum volume. It would be better, I think, if it always erred on matching the louder channel to the quieter one, to avoid being surprised with the volume suddenly being set to maximum. Cheers!

**Comment by jamsinclair** [comment]
Thanks for making an issue @Jimima. 

The app is fairly simplistic, it only adjusts the balance level via an internal audio API. Perhaps this doesn't play nicely with your DAC interface.

Unfortunately I'd be reluctant to add more code around this edge case, unless there is a simple tweak I can make.

**Comment by jamsinclair** [comment]
After some thinking, I want to keep this app's function simple, solving balance drift. This appears to be a separate issue with your device setup.
