### ISSUE TITLE
Randomly closing (crashing?) 

### ISSUE THREAD

**Issue by tgreen7** [jamsinclair/ballast#22]
I am not sure when it closes but my balance will suddenly be off and then I notice that the ballast app is no longer running. I have "Launch at Login" checked and have never manually exited. So I don't know why it would ever quit.

**Comment by jamsinclair** [comment]
Thanks @tgreen7, what version of Ballast are you running?

You can check by:
1. Starting the app
2. Click the menu bar icon
3. Click `About`, the version will be in the displayed window.

**Comment by jamsinclair** [comment]
@tgreen7 does this still happen to you? Happy to help 😺

**Comment by tgreen7** [comment]
I am on version 1.1.0-beta

**Comment by tgreen7** [comment]
It still does happen infrequently.

**Comment by jamsinclair** [comment]
@tgreen7 Ah yes that was a bug in the older version. 

To upgrade to latest version please:
1. If the app is running, select the `Quit` option from the dropdown menu
2. Delete `ballast.app` from your `Applications` folder
3. [Download the latest version, v1.2.1,](https://github.com/jamsinclair/ballast/releases/latest) and copy to your `Applications` folder

That should resolve your issue 😄. I'll close this issue for now.

**Comment by tgreen7** [comment]
Sweet! Ill give that a shot.
