### ISSUE TITLE
On MacOS 10.15 balance is centred visually but real audio output is not.

### ISSUE THREAD

**Issue by haiodo** [jamsinclair/ballast#23]
This happening on On Developer Beta 1:
On MacOS 10.15 balance is centred visually but real audio output is not.

Thanks for a nice tool.

**Comment by jamsinclair** [comment]
@haiodo Thanks for the heads up, will look into when I'm brave enough to upgrade 😬

**Comment by haiodo** [comment]
@jamsinclair I probable will try to create PR, I've waiting for my MacBook to return from service in few days.

**Comment by jamsinclair** [comment]
@haiodo go for it! Much appreciated. Shout out if you need anything.

**Comment by jamsinclair** [comment]
@haiodo I haven't experienced this on the public release of Catalina.

I can replicate this only when manually setting the balance to the extreme of left or right via the Sound System Preferences UI, which is an existing issue. 

Closing for now!

**Comment by simmac** [comment]
I'm experiencing this problem. Sometimes when changing the volume the audio is only on the left or right side, changing the (centered) balance slider does nothing. Only fix is to change the volume until it's centered again. 
Seems like a slightly different bug than the original one.

**Comment by jamsinclair** [comment]
@simmac Thanks for reporting.

Some questions to help us debug further:
- Is this happening on MacOS Catalina? Which version of OS?
- Do you have a unique audio setup? i.e. using special headphones, audio interface etc.
