### ISSUE TITLE
Option to set volume

### ISSUE THREAD

**Issue by ckesc** [jamsinclair/ballast#26]
I use Ballast for Google Pixel buds balance corrections. But for some reason it resets it's volume to max. 

Please add option to set volume to some predefined level when correction balance.

**Comment by jamsinclair** [comment]
Thanks for the suggestion. For this project I want to stick to the simplicity of what this software tries to solve, which is only stopping balance drift.

It sounds like there is a need for an audio app with more fine grained control of its properties 🤔 . I do wonder if anyone else has tried to solve it?
