### ISSUE TITLE
Continuously corrects on a loop whenever balance changes

### ISSUE THREAD

**Issue by OIRNOIR** [jamsinclair/ballast#30]
When the app first starts up when the balance is 0, it works as intended. The first time the balance is adjusted however, it goes into an infinite loop correcting and re-correcting the balance, until it finally seems to crash (or maybe that was a fluke, cannot reproduce the crashing behavior).

**Comment by OIRNOIR** [comment]
I saw issue #29, that does not seem to be the case when downloaded directly from Github.

**Comment by jamsinclair** [comment]
Thanks for the report @OIRNOIR. Can you think of any further steps to help replicate the infinite loop on correction?

In the code we use a debounce approach to prevent this siutation from occurring.

Do you have any other software running that might also be updating the device balance?

**Comment by OIRNOIR** [comment]
No I do not have any other software that might be updating the device balance. I'm not sure if I can replicate this as I started this issue over 2 months ago, but I will get back to you with details if I can find any more.

**Comment by OIRNOIR** [comment]
Stale
