### ISSUE TITLE
Balance to the lowest level 

### ISSUE THREAD

**Issue by theok-nice** [jamsinclair/ballast#32]
When my audio goes out of balance, one channel goes to 100% and the other channel stays on the original level. 

When Ballast kicks in, it corrects the volume towards the channel with the highest value. Is there a way to configure the app to balance towards the lowest value? 

For example, in latest version of the app if right channel is on 20% and left channel is on 50%, ballast will set right channel to 50%. 

I am proposing an new option in the app, if right channel is on 20% and left channel is on 50%, ballast would set left channel to 20%. 

Thank you for your time

**Comment by jamsinclair** [comment]
This app can't access the balance at that granularity. The Core Audio API only gives us access to the "virtual master balance". The master balance is controlled in terms of a single percentage value. 0% being balanced completely left, 100% being completely right, across all channels. 

I appreciate the raising of this issue, however I want to keep this app simple in its purpose and use. I'll close this issue for the time being.

If the repo is helpful in any way of achieving your aim, feel free to fork and mess around!
