### ISSUE TITLE
Option for disabling toolbar icon?

### ISSUE THREAD

**Issue by PatrykDampc** [jamsinclair/ballast#5]
I like keeping my desktop as clean and minimal as I can, so i would be so grateful if there could be some option for disabling that toolbar icon, because Your app is completely autonomous so I don't need to interact with it in any time

**Comment by jamsinclair** [comment]
Totally agree, will look into and scope this out when I get a chance.

**Comment by jamsinclair** [comment]
@PatrykDampc I've got a quick beta release here:
https://github.com/jamsinclair/ballast/releases/download/untagged-901589362163f4e8c9dc/ballast-1.1.0-beta.zip

Give it a try and let me know if that works well for you. 

If you need to restore the icon to your toolbar, re-open the app again. You'll be shown a window with options to restore the icon or keep running in the background:
<img width="576" alt="screen shot 2018-10-20 at 11 58 22 pm" src="https://user-images.githubusercontent.com/5964236/47257081-1a04c980-d4c4-11e8-990a-2c40033962a8.png">

**Comment by PatrykDampc** [comment]
Looks like it works, and it's great to have feedback from You!

**Comment by jamsinclair** [comment]
Initial Feature added in [v1.1.0](https://github.com/jamsinclair/ballast/releases/tag/v1.1.0)
