### ISSUE TITLE
Error: `Unable to load Info.plist exceptions (eGPUOverrides)`

### ISSUE THREAD

**Issue by jamsinclair** [jamsinclair/ballast#6]
Ballast on start always throws error `Unable to load Info.plist exceptions (eGPUOverrides)`.

Apparently Mojave specific bug to do with the likes of Launchservices.
Discussion here on StackOverflow: https://stackoverflow.com/questions/52507950/unable-to-load-info-plist-error-xcode-10-under-macos-10-14-mojave

**Comment by alex-taffe** [comment]
Pretty sure this was an Xcode 10 bug that was fixed in 10.2

**Comment by jamsinclair** [comment]
@alex-taffe Thanks for the heads up. Compiled with latest xcode and seems ok now 👌
